# Generated by Django 3.2.9 on 2021-12-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('link', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
            ],
        ),
    ]
