# Generated by Django 3.2.9 on 2021-12-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(upload_to='posts/%Y/%m/%d/'),
        ),
    ]
