# Generated by Django 3.2.9 on 2022-02-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_event_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('link', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='blogs/%Y/%m/%d/')),
                ('author', models.CharField(max_length=50)),
                ('date_published', models.DateField()),
            ],
        ),
    ]
